/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.model.Aviso;
import br.com.model.Relatorio;
import br.com.util.Retorno;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Israel Araújo
 */
public class MainFrame extends javax.swing.JFrame {

    private Relatorio relatorio;
    private final DefaultListModel<BigDecimal> valoresRelatorio = new DefaultListModel<>();
    private final DefaultListModel<Aviso> avisos = new DefaultListModel<>();
    private final DefaultListModel<BigDecimal> valoresDetalhamento = new DefaultListModel<>();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.valoresList.setModel(valoresRelatorio);
        this.avisosList.setModel(avisos);
        this.detalhamentoList.setModel(valoresDetalhamento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        relatorioInternalFrame = new javax.swing.JInternalFrame();
        dataLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        restanteLabel = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        valoresList = new javax.swing.JList();
        relatorioLabelList = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        avisosList = new javax.swing.JList();
        detalhamentoLabelList = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        detalhamentoList = new javax.swing.JList();
        avisosDetalhamentoList = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Identificador de avisos");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/view/icons/png/dollar179.png")));

        relatorioInternalFrame.setClosable(true);
        relatorioInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        relatorioInternalFrame.setIconifiable(true);
        relatorioInternalFrame.setMaximizable(true);
        relatorioInternalFrame.setResizable(true);
        relatorioInternalFrame.setTitle("Arquivo retorno");
        relatorioInternalFrame.setAutoscrolls(true);
        relatorioInternalFrame.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/icons/png/folder12.png"))); // NOI18N
        relatorioInternalFrame.setVisible(true);

        dataLabel.setText("Data");

        totalLabel.setText("Total");

        restanteLabel.setText("Restante");

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        valoresList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        valoresList.setToolTipText("");
        jScrollPane1.setViewportView(valoresList);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        relatorioLabelList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relatorioLabelList.setText("Relatório");
        relatorioLabelList.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel2.add(relatorioLabelList, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setLeftComponent(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(null);

        avisosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        avisosList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avisosListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(avisosList);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        detalhamentoLabelList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detalhamentoLabelList.setText("Avisos encontrados");
        detalhamentoLabelList.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel3.add(detalhamentoLabelList, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setRightComponent(jPanel3);

        jMenu2.setText("Arquivo");
        jMenu2.setEnabled(true);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/icons/png/magnifier1.png"))); // NOI18N
        jMenuItem2.setText("Buscar");
        jMenuItem2.setEnabled(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/icons/png/recycle8.png"))); // NOI18N
        jMenuItem3.setText("Limpar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        relatorioInternalFrame.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout relatorioInternalFrameLayout = new javax.swing.GroupLayout(relatorioInternalFrame.getContentPane());
        relatorioInternalFrame.getContentPane().setLayout(relatorioInternalFrameLayout);
        relatorioInternalFrameLayout.setHorizontalGroup(
            relatorioInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relatorioInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(relatorioInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restanteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addComponent(dataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSplitPane1)
                    .addGroup(relatorioInternalFrameLayout.createSequentialGroup()
                        .addComponent(totalLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        relatorioInternalFrameLayout.setVerticalGroup(
            relatorioInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relatorioInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restanteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        desktopPane.add(relatorioInternalFrame);
        relatorioInternalFrame.setBounds(10, 11, 710, 410);

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 21));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 21));
        jPanel1.setPreferredSize(new java.awt.Dimension(690, 21));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(204, 204, 204)));
        jPanel4.setMaximumSize(new java.awt.Dimension(200, 32767));
        jPanel4.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 437));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setBorder(null);

        detalhamentoList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(detalhamentoList);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        avisosDetalhamentoList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisosDetalhamentoList.setText("Valores do aviso");
        avisosDetalhamentoList.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel4.add(avisosDetalhamentoList, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel4, java.awt.BorderLayout.EAST);

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/icons/png/archive7.png"))); // NOI18N
        jMenuItem1.setText("Arquivo retorno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Exibir");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/view/icons/png/dark29.png"))); // NOI18N
        jMenuItem4.setText("Relatório de retorno");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(946, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showOpenDialog(null);
        if (i == JFileChooser.APPROVE_OPTION) {
            try {
                this.relatorio = Retorno.getRetorno(file.getSelectedFile().toString());
                update();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Arquivo não encontrado");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Data do arquivo inválida");
            } catch (UnsupportedOperationException ex) {
                JOptionPane.showMessageDialog(null, "Erro ocorrido ao adicionar valores no arquivo\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Find f = new Find(this, true, this.relatorio);
        f.setVisible(true);
        update();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void avisosListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avisosListMouseClicked
        // TODO add your handling code here:
        int index = avisosList.getSelectedIndex();
        if (index != -1) {
            this.detalhamentoList.updateUI();
            this.valoresList.updateUI();
            valoresDetalhamento.clear();
            avisos.get(index).getValores().stream().forEach((f) -> {
                valoresDetalhamento.addElement(f);
            });
        }
    }//GEN-LAST:event_avisosListMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        relatorio = new Relatorio(new BigDecimal(0), new Date());
        update();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        relatorioInternalFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void update() {
        this.dataLabel.setText("Data: " + new SimpleDateFormat("dd/MM/yyyy").format(this.relatorio.getData()));
        this.totalLabel.setText("Total: " + new DecimalFormat("R$ #,##0.00").format(this.relatorio.getValorTotal()));
        this.restanteLabel.setText("Restante: " + new DecimalFormat("R$ #,##0.00").format(this.relatorio.valorRestante()));
        this.valoresRelatorio.clear();
        this.avisos.clear();
        this.relatorio.getValores().stream().forEach((f) -> {
            this.valoresRelatorio.addElement(f);
        });
        this.relatorio.getRemovidos().stream().forEach((a) -> {
            this.avisos.addElement(a);
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainFrame m = new MainFrame();
            m.setExtendedState(JFrame.MAXIMIZED_BOTH);
            m.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisosDetalhamentoList;
    private javax.swing.JList avisosList;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel detalhamentoLabelList;
    private javax.swing.JList detalhamentoList;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JInternalFrame relatorioInternalFrame;
    private javax.swing.JLabel relatorioLabelList;
    private javax.swing.JLabel restanteLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JList valoresList;
    // End of variables declaration//GEN-END:variables
}
